version: "3.7"

services:
  pg_database:
    image: postgres
    container_name: pg_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=su
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=whatsapplite
    volumes:
    - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
